In [1]:
import numpy as np

In [2]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [3]:
def rbf(x, l, gamma = 0.3):
    return np.exp(-gamma*(x-l)**2)

In [6]:
np.round(rbf(x, l=-2), 3)

array([0.301, 0.741, 1.   , 0.741, 0.301, 0.067, 0.008, 0.001, 0.   ])

In [7]:
np.round(rbf(x, l=1), 3)

array([0.001, 0.008, 0.067, 0.301, 0.741, 1.   , 0.741, 0.301, 0.067])